# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\projects\serialCom\res\serialCom.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_serialDlg(object):
    def setupUi(self, serialDlg):
        serialDlg.setObjectName("serialDlg")
        serialDlg.resize(580, 468)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(serialDlg.sizePolicy().hasHeightForWidth())
        serialDlg.setSizePolicy(sizePolicy)
        self.groupBox = QtWidgets.QGroupBox(serialDlg)
        self.groupBox.setGeometry(QtCore.QRect(20, 140, 541, 281))
        self.groupBox.setObjectName("groupBox")
        self.recvHexEdit = QtWidgets.QLineEdit(self.groupBox)
        self.recvHexEdit.setGeometry(QtCore.QRect(130, 30, 391, 30))
        self.recvHexEdit.setReadOnly(True)
        self.recvHexEdit.setObjectName("recvHexEdit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 110, 30))
        self.label.setObjectName("label")
        self.transValEdit = QtWidgets.QLineEdit(self.groupBox)
        self.transValEdit.setGeometry(QtCore.QRect(130, 80, 150, 30))
        self.transValEdit.setReadOnly(True)
        self.transValEdit.setObjectName("transValEdit")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 110, 30))
        self.label_2.setObjectName("label_2")
        self.tightTorqueEdit = QtWidgets.QLineEdit(self.groupBox)
        self.tightTorqueEdit.setGeometry(QtCore.QRect(130, 130, 150, 30))
        self.tightTorqueEdit.setReadOnly(True)
        self.tightTorqueEdit.setObjectName("tightTorqueEdit")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 110, 30))
        self.label_3.setObjectName("label_3")
        self.tightAngleEdit = QtWidgets.QLineEdit(self.groupBox)
        self.tightAngleEdit.setGeometry(QtCore.QRect(130, 180, 150, 30))
        self.tightAngleEdit.setReadOnly(True)
        self.tightAngleEdit.setObjectName("tightAngleEdit")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 111, 31))
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(20, 230, 110, 30))
        self.label_10.setObjectName("label_10")
        self.flagBitEdit = QtWidgets.QLineEdit(self.groupBox)
        self.flagBitEdit.setGeometry(QtCore.QRect(130, 230, 101, 30))
        self.flagBitEdit.setReadOnly(True)
        self.flagBitEdit.setObjectName("flagBitEdit")
        self.flagBitLabel = QtWidgets.QLabel(self.groupBox)
        self.flagBitLabel.setGeometry(QtCore.QRect(250, 230, 30, 30))
        self.flagBitLabel.setStyleSheet("")
        self.flagBitLabel.setText("")
        self.flagBitLabel.setObjectName("flagBitLabel")
        self.dataTable = QtWidgets.QTableWidget(self.groupBox)
        self.dataTable.setGeometry(QtCore.QRect(290, 80, 231, 181))
        self.dataTable.setObjectName("dataTable")
        self.dataTable.setColumnCount(3)
        self.dataTable.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(2, item)
        self.dataTable.horizontalHeader().setDefaultSectionSize(80)
        self.groupBox_2 = QtWidgets.QGroupBox(serialDlg)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 541, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.openBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.openBtn.setGeometry(QtCore.QRect(310, 20, 100, 30))
        self.openBtn.setObjectName("openBtn")
        self.portEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.portEdit.setGeometry(QtCore.QRect(120, 20, 150, 30))
        self.portEdit.setReadOnly(False)
        self.portEdit.setObjectName("portEdit")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 110, 30))
        self.label_7.setObjectName("label_7")
        self.closeBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.closeBtn.setGeometry(QtCore.QRect(310, 60, 100, 30))
        self.closeBtn.setObjectName("closeBtn")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 60, 110, 30))
        self.label_8.setObjectName("label_8")
        self.baudrateEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.baudrateEdit.setGeometry(QtCore.QRect(120, 60, 150, 30))
        self.baudrateEdit.setReadOnly(False)
        self.baudrateEdit.setObjectName("baudrateEdit")
        self.stopReadBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.stopReadBtn.setGeometry(QtCore.QRect(420, 60, 100, 30))
        self.stopReadBtn.setObjectName("stopReadBtn")
        self.startReadBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.startReadBtn.setGeometry(QtCore.QRect(420, 20, 100, 30))
        self.startReadBtn.setObjectName("startReadBtn")
        self.infoLabel = QtWidgets.QLabel(serialDlg)
        self.infoLabel.setGeometry(QtCore.QRect(20, 430, 541, 30))
        self.infoLabel.setText("")
        self.infoLabel.setObjectName("infoLabel")

        self.retranslateUi(serialDlg)
        QtCore.QMetaObject.connectSlotsByName(serialDlg)

    def retranslateUi(self, serialDlg):
        _translate = QtCore.QCoreApplication.translate
        serialDlg.setWindowTitle(_translate("serialDlg", "Value Reader"))
        self.groupBox.setTitle(_translate("serialDlg", "数据信息:"))
        self.label.setText(_translate("serialDlg", "接收信息(Hex):"))
        self.label_2.setText(_translate("serialDlg", "整合数值(int):"))
        self.label_3.setText(_translate("serialDlg", "拧紧力矩(N.m):"))
        self.label_4.setText(_translate("serialDlg", "拧紧角度(degree):"))
        self.label_10.setText(_translate("serialDlg", "拧紧状态:"))
        item = self.dataTable.verticalHeaderItem(0)
        item.setText(_translate("serialDlg", "1"))
        item = self.dataTable.verticalHeaderItem(1)
        item.setText(_translate("serialDlg", "2"))
        item = self.dataTable.verticalHeaderItem(2)
        item.setText(_translate("serialDlg", "3"))
        item = self.dataTable.verticalHeaderItem(3)
        item.setText(_translate("serialDlg", "4"))
        item = self.dataTable.verticalHeaderItem(4)
        item.setText(_translate("serialDlg", "5"))
        item = self.dataTable.verticalHeaderItem(5)
        item.setText(_translate("serialDlg", "6"))
        item = self.dataTable.verticalHeaderItem(6)
        item.setText(_translate("serialDlg", "7"))
        item = self.dataTable.verticalHeaderItem(7)
        item.setText(_translate("serialDlg", "8"))
        item = self.dataTable.verticalHeaderItem(8)
        item.setText(_translate("serialDlg", "9"))
        item = self.dataTable.verticalHeaderItem(9)
        item.setText(_translate("serialDlg", "10"))
        item = self.dataTable.horizontalHeaderItem(0)
        item.setText(_translate("serialDlg", "标志位"))
        item = self.dataTable.horizontalHeaderItem(1)
        item.setText(_translate("serialDlg", "拧紧力矩"))
        item = self.dataTable.horizontalHeaderItem(2)
        item.setText(_translate("serialDlg", "拧紧角度"))
        self.groupBox_2.setTitle(_translate("serialDlg", "串口设置:"))
        self.openBtn.setText(_translate("serialDlg", "打开串口"))
        self.label_7.setText(_translate("serialDlg", "COM端口:"))
        self.closeBtn.setText(_translate("serialDlg", "关闭串口"))
        self.label_8.setText(_translate("serialDlg", "波特率:"))
        self.stopReadBtn.setText(_translate("serialDlg", "停止读取"))
        self.startReadBtn.setText(_translate("serialDlg", "开始读取"))

