# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\projects\serialCom\serialcom\res\serialcom.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_serialDlg(object):
    def setupUi(self, serialDlg):
        serialDlg.setObjectName("serialDlg")
        serialDlg.resize(1024, 725)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(serialDlg.sizePolicy().hasHeightForWidth())
        serialDlg.setSizePolicy(sizePolicy)
        self.groupBox = QtWidgets.QGroupBox(serialDlg)
        self.groupBox.setGeometry(QtCore.QRect(10, 5, 501, 281))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.recvHexEdit = QtWidgets.QLineEdit(self.groupBox)
        self.recvHexEdit.setGeometry(QtCore.QRect(170, 30, 310, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.recvHexEdit.setFont(font)
        self.recvHexEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.recvHexEdit.setReadOnly(True)
        self.recvHexEdit.setObjectName("recvHexEdit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 155, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.transValEdit = QtWidgets.QLineEdit(self.groupBox)
        self.transValEdit.setGeometry(QtCore.QRect(170, 80, 310, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.transValEdit.setFont(font)
        self.transValEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.transValEdit.setReadOnly(True)
        self.transValEdit.setObjectName("transValEdit")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 155, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tightTorqueEdit = QtWidgets.QLineEdit(self.groupBox)
        self.tightTorqueEdit.setGeometry(QtCore.QRect(170, 130, 310, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tightTorqueEdit.setFont(font)
        self.tightTorqueEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tightTorqueEdit.setReadOnly(True)
        self.tightTorqueEdit.setObjectName("tightTorqueEdit")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 155, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tightAngleEdit = QtWidgets.QLineEdit(self.groupBox)
        self.tightAngleEdit.setGeometry(QtCore.QRect(170, 180, 210, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tightAngleEdit.setFont(font)
        self.tightAngleEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tightAngleEdit.setReadOnly(True)
        self.tightAngleEdit.setObjectName("tightAngleEdit")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 155, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 230, 155, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.flagBitEdit = QtWidgets.QLineEdit(self.groupBox)
        self.flagBitEdit.setGeometry(QtCore.QRect(170, 230, 210, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.flagBitEdit.setFont(font)
        self.flagBitEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.flagBitEdit.setReadOnly(True)
        self.flagBitEdit.setObjectName("flagBitEdit")
        self.flagBitLabel = QtWidgets.QLabel(self.groupBox)
        self.flagBitLabel.setGeometry(QtCore.QRect(395, 180, 85, 85))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.flagBitLabel.setFont(font)
        self.flagBitLabel.setStyleSheet("color: rgb(0, 255, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.flagBitLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.flagBitLabel.setObjectName("flagBitLabel")
        self.groupBox_2 = QtWidgets.QGroupBox(serialDlg)
        self.groupBox_2.setGeometry(QtCore.QRect(519, 5, 491, 131))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.openBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.openBtn.setGeometry(QtCore.QRect(240, 30, 110, 40))
        self.openBtn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.openBtn.setAutoDefault(False)
        self.openBtn.setObjectName("openBtn")
        self.portEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.portEdit.setGeometry(QtCore.QRect(110, 32, 120, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.portEdit.setFont(font)
        self.portEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.portEdit.setReadOnly(False)
        self.portEdit.setObjectName("portEdit")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 30, 85, 35))
        self.label_7.setObjectName("label_7")
        self.closeBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.closeBtn.setGeometry(QtCore.QRect(240, 80, 110, 40))
        self.closeBtn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.closeBtn.setAutoDefault(False)
        self.closeBtn.setObjectName("closeBtn")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 80, 85, 35))
        self.label_8.setObjectName("label_8")
        self.baudrateEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.baudrateEdit.setGeometry(QtCore.QRect(110, 82, 120, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.baudrateEdit.setFont(font)
        self.baudrateEdit.setReadOnly(False)
        self.baudrateEdit.setObjectName("baudrateEdit")
        self.stopReadBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.stopReadBtn.setGeometry(QtCore.QRect(370, 80, 110, 40))
        self.stopReadBtn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.stopReadBtn.setAutoDefault(False)
        self.stopReadBtn.setObjectName("stopReadBtn")
        self.startReadBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.startReadBtn.setGeometry(QtCore.QRect(370, 30, 110, 40))
        self.startReadBtn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.startReadBtn.setAutoDefault(False)
        self.startReadBtn.setObjectName("startReadBtn")
        self.groupBox_3 = QtWidgets.QGroupBox(serialDlg)
        self.groupBox_3.setGeometry(QtCore.QRect(520, 150, 491, 131))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.barcodeEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.barcodeEdit.setGeometry(QtCore.QRect(100, 30, 380, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.barcodeEdit.setFont(font)
        self.barcodeEdit.setReadOnly(True)
        self.barcodeEdit.setObjectName("barcodeEdit")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 85, 40))
        self.label_5.setObjectName("label_5")
        self.barcodeEdit_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.barcodeEdit_2.setGeometry(QtCore.QRect(100, 80, 380, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.barcodeEdit_2.setFont(font)
        self.barcodeEdit_2.setReadOnly(True)
        self.barcodeEdit_2.setObjectName("barcodeEdit_2")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 80, 85, 40))
        self.label_11.setObjectName("label_11")
        self.groupBox_4 = QtWidgets.QGroupBox(serialDlg)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 295, 501, 381))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupCountEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.groupCountEdit.setGeometry(QtCore.QRect(170, 30, 211, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupCountEdit.setFont(font)
        self.groupCountEdit.setObjectName("groupCountEdit")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(20, 35, 141, 30))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(390, 30, 91, 35))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.dataListPanel = QtWidgets.QListWidget(self.groupBox_4)
        self.dataListPanel.setGeometry(QtCore.QRect(20, 80, 461, 291))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.dataListPanel.setFont(font)
        self.dataListPanel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dataListPanel.setObjectName("dataListPanel")
        self.infoLabel = QtWidgets.QLabel(serialDlg)
        self.infoLabel.setGeometry(QtCore.QRect(10, 680, 1001, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoLabel.sizePolicy().hasHeightForWidth())
        self.infoLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.infoLabel.setFont(font)
        self.infoLabel.setObjectName("infoLabel")
        self.groupBox_6 = QtWidgets.QGroupBox(serialDlg)
        self.groupBox_6.setGeometry(QtCore.QRect(520, 295, 491, 381))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.productInfoPanel = QtWidgets.QListWidget(self.groupBox_6)
        self.productInfoPanel.setGeometry(QtCore.QRect(10, 80, 471, 291))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.productInfoPanel.setFont(font)
        self.productInfoPanel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.productInfoPanel.setObjectName("productInfoPanel")
        self.preBtn = QtWidgets.QPushButton(self.groupBox_6)
        self.preBtn.setGeometry(QtCore.QRect(190, 25, 120, 45))
        self.preBtn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.preBtn.setAutoDefault(False)
        self.preBtn.setObjectName("preBtn")
        self.nextBtn = QtWidgets.QPushButton(self.groupBox_6)
        self.nextBtn.setGeometry(QtCore.QRect(360, 25, 120, 45))
        self.nextBtn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.nextBtn.setAutoDefault(False)
        self.nextBtn.setObjectName("nextBtn")
        self.currBtn = QtWidgets.QPushButton(self.groupBox_6)
        self.currBtn.setGeometry(QtCore.QRect(10, 25, 120, 45))
        self.currBtn.setAutoDefault(False)
        self.currBtn.setObjectName("currBtn")

        self.retranslateUi(serialDlg)
        QtCore.QMetaObject.connectSlotsByName(serialDlg)

    def retranslateUi(self, serialDlg):
        _translate = QtCore.QCoreApplication.translate
        serialDlg.setWindowTitle(_translate("serialDlg", "Value Reader"))
        self.groupBox.setTitle(_translate("serialDlg", "数据信息:"))
        self.label.setText(_translate("serialDlg", "接收信息(Hex):"))
        self.label_2.setText(_translate("serialDlg", "整合数值(int):"))
        self.label_3.setText(_translate("serialDlg", "拧紧力矩(N.m):"))
        self.label_4.setText(_translate("serialDlg", "拧紧角度(度):"))
        self.label_10.setText(_translate("serialDlg", "拧紧状态:"))
        self.flagBitLabel.setText(_translate("serialDlg", "OK"))
        self.groupBox_2.setTitle(_translate("serialDlg", "串口设置:"))
        self.openBtn.setText(_translate("serialDlg", "打开串口"))
        self.label_7.setText(_translate("serialDlg", "COM端口:"))
        self.closeBtn.setText(_translate("serialDlg", "关闭串口"))
        self.label_8.setText(_translate("serialDlg", "波特率:"))
        self.stopReadBtn.setText(_translate("serialDlg", "停止读取"))
        self.startReadBtn.setText(_translate("serialDlg", "开始读取"))
        self.groupBox_3.setTitle(_translate("serialDlg", "条形码扫描:"))
        self.label_5.setText(_translate("serialDlg", "条形码1:"))
        self.label_11.setText(_translate("serialDlg", "条形码2:"))
        self.groupBox_4.setTitle(_translate("serialDlg", "数据显示:"))
        self.label_6.setText(_translate("serialDlg", "螺丝拧紧数目:"))
        self.label_9.setText(_translate("serialDlg", "(个/组)"))
        self.infoLabel.setText(_translate("serialDlg", "信息:"))
        self.groupBox_6.setTitle(_translate("serialDlg", "数据查看:"))
        self.preBtn.setText(_translate("serialDlg", "查看上一组"))
        self.nextBtn.setText(_translate("serialDlg", "查看下一组"))
        self.currBtn.setText(_translate("serialDlg", "查看数据"))

