# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\aron\AppData\Roaming\aronWorkSpace\arvinGithub\projects\glassDetect\res\glassdetectdlg.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_glassDetectDlg(object):
    def setupUi(self, glassDetectDlg):
        glassDetectDlg.setObjectName("glassDetectDlg")
        glassDetectDlg.resize(1024, 768)
        self.imageViewLabel = QtWidgets.QLabel(glassDetectDlg)
        self.imageViewLabel.setGeometry(QtCore.QRect(10, 10, 500, 500))
        self.imageViewLabel.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.imageViewLabel.setText("")
        self.imageViewLabel.setObjectName("imageViewLabel")
        self.paramSettingBtn = QtWidgets.QPushButton(glassDetectDlg)
        self.paramSettingBtn.setGeometry(QtCore.QRect(300, 550, 170, 50))
        self.paramSettingBtn.setObjectName("paramSettingBtn")
        self.StartBtn = QtWidgets.QPushButton(glassDetectDlg)
        self.StartBtn.setGeometry(QtCore.QRect(300, 610, 170, 50))
        self.StartBtn.setObjectName("StartBtn")
        self.stopBtn = QtWidgets.QPushButton(glassDetectDlg)
        self.stopBtn.setGeometry(QtCore.QRect(300, 670, 170, 50))
        self.stopBtn.setObjectName("stopBtn")
        self.groupBox = QtWidgets.QGroupBox(glassDetectDlg)
        self.groupBox.setGeometry(QtCore.QRect(10, 520, 271, 201))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 120, 30))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 120, 30))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 120, 120, 30))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 160, 120, 30))
        self.label_6.setObjectName("label_6")
        self.sumEdit = QtWidgets.QLineEdit(self.groupBox)
        self.sumEdit.setGeometry(QtCore.QRect(130, 40, 120, 30))
        self.sumEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.sumEdit.setReadOnly(True)
        self.sumEdit.setObjectName("sumEdit")
        self.goodNumEdit = QtWidgets.QLineEdit(self.groupBox)
        self.goodNumEdit.setGeometry(QtCore.QRect(130, 80, 120, 30))
        self.goodNumEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.goodNumEdit.setReadOnly(True)
        self.goodNumEdit.setObjectName("goodNumEdit")
        self.badNumEdit = QtWidgets.QLineEdit(self.groupBox)
        self.badNumEdit.setGeometry(QtCore.QRect(130, 120, 120, 30))
        self.badNumEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.badNumEdit.setReadOnly(True)
        self.badNumEdit.setObjectName("badNumEdit")
        self.goodPercentEdit = QtWidgets.QLineEdit(self.groupBox)
        self.goodPercentEdit.setGeometry(QtCore.QRect(130, 160, 120, 30))
        self.goodPercentEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.goodPercentEdit.setReadOnly(True)
        self.goodPercentEdit.setObjectName("goodPercentEdit")
        self.statusLabel = QtWidgets.QLabel(glassDetectDlg)
        self.statusLabel.setGeometry(QtCore.QRect(0, 730, 1024, 38))
        self.statusLabel.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.dstImageLabel = QtWidgets.QLabel(glassDetectDlg)
        self.dstImageLabel.setGeometry(QtCore.QRect(520, 10, 500, 500))
        self.dstImageLabel.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.dstImageLabel.setText("")
        self.dstImageLabel.setObjectName("dstImageLabel")
        self.loadImageBtn = QtWidgets.QPushButton(glassDetectDlg)
        self.loadImageBtn.setGeometry(QtCore.QRect(940, 560, 81, 31))
        self.loadImageBtn.setObjectName("loadImageBtn")
        self.imagePathEdit = QtWidgets.QLineEdit(glassDetectDlg)
        self.imagePathEdit.setGeometry(QtCore.QRect(590, 560, 340, 30))
        self.imagePathEdit.setObjectName("imagePathEdit")
        self.label = QtWidgets.QLabel(glassDetectDlg)
        self.label.setGeometry(QtCore.QRect(520, 560, 60, 30))
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(glassDetectDlg)
        self.groupBox_2.setGeometry(QtCore.QRect(510, 610, 501, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 40, 30))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(40, 30, 100, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 70, 100, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 40, 30))
        self.label_7.setObjectName("label_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 30, 100, 30))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(160, 30, 40, 30))
        self.label_8.setObjectName("label_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 70, 100, 30))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(160, 70, 40, 30))
        self.label_9.setObjectName("label_9")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(390, 30, 100, 30))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(320, 30, 65, 30))
        self.label_10.setObjectName("label_10")

        self.retranslateUi(glassDetectDlg)
        QtCore.QMetaObject.connectSlotsByName(glassDetectDlg)

    def retranslateUi(self, glassDetectDlg):
        _translate = QtCore.QCoreApplication.translate
        glassDetectDlg.setWindowTitle(_translate("glassDetectDlg", "玻璃检测"))
        self.paramSettingBtn.setText(_translate("glassDetectDlg", "参数设定"))
        self.StartBtn.setText(_translate("glassDetectDlg", "开始检测"))
        self.stopBtn.setText(_translate("glassDetectDlg", "停止检测"))
        self.groupBox.setTitle(_translate("glassDetectDlg", "检测结果"))
        self.label_3.setText(_translate("glassDetectDlg", "检测总数目(个):"))
        self.label_4.setText(_translate("glassDetectDlg", "检测合格数目(个):"))
        self.label_5.setText(_translate("glassDetectDlg", "检测排除数目(个):"))
        self.label_6.setText(_translate("glassDetectDlg", "检测合格率(%):"))
        self.sumEdit.setText(_translate("glassDetectDlg", "0"))
        self.goodNumEdit.setText(_translate("glassDetectDlg", "0"))
        self.badNumEdit.setText(_translate("glassDetectDlg", "0"))
        self.goodPercentEdit.setText(_translate("glassDetectDlg", "0.000"))
        self.loadImageBtn.setText(_translate("glassDetectDlg", "..."))
        self.label.setText(_translate("glassDetectDlg", "图片路径:"))
        self.groupBox_2.setTitle(_translate("glassDetectDlg", "数据:"))
        self.label_2.setText(_translate("glassDetectDlg", "Min"))
        self.label_7.setText(_translate("glassDetectDlg", "Max"))
        self.label_8.setText(_translate("glassDetectDlg", "Mean"))
        self.label_9.setText(_translate("glassDetectDlg", "Diff"))
        self.label_10.setText(_translate("glassDetectDlg", "Eevaluate"))

