# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\aron\AppData\Roaming\aronWorkSpace\arvinGithub\projects\glassDetect\res\glassdetectdlg.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_glassDetectDlg(object):
    def setupUi(self, glassDetectDlg):
        glassDetectDlg.setObjectName("glassDetectDlg")
        glassDetectDlg.resize(853, 768)
        self.imageViewLabel = QtWidgets.QLabel(glassDetectDlg)
        self.imageViewLabel.setGeometry(QtCore.QRect(10, 10, 500, 400))
        self.imageViewLabel.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.imageViewLabel.setText("")
        self.imageViewLabel.setObjectName("imageViewLabel")
        self.statusLabel = QtWidgets.QLabel(glassDetectDlg)
        self.statusLabel.setGeometry(QtCore.QRect(0, 730, 1024, 38))
        self.statusLabel.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.groupBox = QtWidgets.QGroupBox(glassDetectDlg)
        self.groupBox.setGeometry(QtCore.QRect(530, 10, 311, 711))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 100, 30))
        self.label_11.setObjectName("label_11")
        self.downLimitEdit = QtWidgets.QLineEdit(self.groupBox)
        self.downLimitEdit.setGeometry(QtCore.QRect(160, 60, 131, 30))
        self.downLimitEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.downLimitEdit.setReadOnly(True)
        self.downLimitEdit.setObjectName("downLimitEdit")
        self.prevImgBtn = QtWidgets.QPushButton(self.groupBox)
        self.prevImgBtn.setGeometry(QtCore.QRect(160, 105, 131, 40))
        self.prevImgBtn.setObjectName("prevImgBtn")
        self.loadImagePathBtn = QtWidgets.QPushButton(self.groupBox)
        self.loadImagePathBtn.setGeometry(QtCore.QRect(10, 105, 130, 85))
        self.loadImagePathBtn.setObjectName("loadImagePathBtn")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 210, 291, 491))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 110, 30))
        self.label_2.setObjectName("label_2")
        self.minEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.minEdit.setGeometry(QtCore.QRect(150, 30, 120, 30))
        self.minEdit.setReadOnly(True)
        self.minEdit.setObjectName("minEdit")
        self.maxEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.maxEdit.setGeometry(QtCore.QRect(150, 70, 120, 30))
        self.maxEdit.setReadOnly(True)
        self.maxEdit.setObjectName("maxEdit")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 110, 30))
        self.label_7.setObjectName("label_7")
        self.meanEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.meanEdit.setGeometry(QtCore.QRect(150, 110, 120, 30))
        self.meanEdit.setReadOnly(True)
        self.meanEdit.setObjectName("meanEdit")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 110, 110, 30))
        self.label_8.setObjectName("label_8")
        self.diffEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.diffEdit.setGeometry(QtCore.QRect(150, 160, 120, 30))
        self.diffEdit.setReadOnly(True)
        self.diffEdit.setObjectName("diffEdit")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 160, 110, 30))
        self.label_9.setToolTipDuration(-1)
        self.label_9.setObjectName("label_9")
        self.evaluateEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.evaluateEdit.setGeometry(QtCore.QRect(150, 200, 120, 30))
        self.evaluateEdit.setReadOnly(True)
        self.evaluateEdit.setObjectName("evaluateEdit")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 200, 110, 30))
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 60, 100, 30))
        self.label_12.setObjectName("label_12")
        self.upLimitEdit = QtWidgets.QLineEdit(self.groupBox)
        self.upLimitEdit.setGeometry(QtCore.QRect(160, 20, 131, 30))
        self.upLimitEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.upLimitEdit.setReadOnly(True)
        self.upLimitEdit.setObjectName("upLimitEdit")
        self.nextImgBtn = QtWidgets.QPushButton(self.groupBox)
        self.nextImgBtn.setGeometry(QtCore.QRect(160, 150, 131, 40))
        self.nextImgBtn.setObjectName("nextImgBtn")

        self.retranslateUi(glassDetectDlg)
        QtCore.QMetaObject.connectSlotsByName(glassDetectDlg)

    def retranslateUi(self, glassDetectDlg):
        _translate = QtCore.QCoreApplication.translate
        glassDetectDlg.setWindowTitle(_translate("glassDetectDlg", "玻璃检测"))
        self.label_11.setText(_translate("glassDetectDlg", "边缘宽度上限:"))
        self.downLimitEdit.setText(_translate("glassDetectDlg", "0"))
        self.prevImgBtn.setText(_translate("glassDetectDlg", "上一张图片"))
        self.loadImagePathBtn.setText(_translate("glassDetectDlg", "加载图片"))
        self.groupBox_2.setTitle(_translate("glassDetectDlg", "数据:"))
        self.label_2.setText(_translate("glassDetectDlg", "边缘宽度最小值:"))
        self.minEdit.setText(_translate("glassDetectDlg", "0"))
        self.maxEdit.setText(_translate("glassDetectDlg", "0"))
        self.label_7.setText(_translate("glassDetectDlg", "边缘宽度最大值:"))
        self.meanEdit.setText(_translate("glassDetectDlg", "0"))
        self.label_8.setText(_translate("glassDetectDlg", "边缘宽度平均值:"))
        self.diffEdit.setText(_translate("glassDetectDlg", "0"))
        self.label_9.setText(_translate("glassDetectDlg", "边缘最大最小差值:"))
        self.evaluateEdit.setText(_translate("glassDetectDlg", "0"))
        self.label_10.setText(_translate("glassDetectDlg", "边缘宽度估计值:"))
        self.label_12.setText(_translate("glassDetectDlg", "边缘宽度下限:"))
        self.upLimitEdit.setText(_translate("glassDetectDlg", "0"))
        self.nextImgBtn.setText(_translate("glassDetectDlg", "下一张图片"))

